@jwt = eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Fn_OIMIXbGc_ZZgD.jt8DTBJ9l_sBaqIf8_ged7ewcMXOrWKk5LTgO6_ri2xpBTBRia--8LDkUFg1gcdhAg93uGChjEz3iTAj7psg9mfrZGxbXwKo1gqLNDMZPYjtKp-EK7r--4CtmI48X995qeqhV_fSwrXX5dAzRhc7mlMehowrniqL9Y6t7QBRnFYo1RipdK5ineadmRgk2Ype4c3e-enOcff4usafQMtAeVwKWLuBosIvwra_MdIJJYBciC3JvH7IxBXvq6LTtvC4PzwoT_mRcBO9B5ELyPqxvPm9lCnhT-vpKLJ1RV7kjQkLbVpQpmGsjhbibb9iSYkLEtkBdGn7BOTNskb-CS6rPaXPqYKwIV-cAq06Zx3DOD0M5S6QN_btvWLN-oNgN2uvqEY7bTsN6Dul-JvwWuWYdAy2jDzPKvHvY0HaLPCMylPOBtf_wsSYRsCsWB6h-4FSrcvWmJwknzJ5tIwISsQK2yrrVoYcKgKOYer8PzN-9j7-BO5f6HfW4TOdazFxYyGhtLC6-LjicvWqLJUjYrW-CBU7arHXWUuJSzI_iukgzgEsA8t9SKtKfRl5D6azXsAYou3wwpaK6hBxpc7bfZ48YIvbaKHhs8exvtsVL20.rx-kBl6WHS8hsoU871mQOg
GET http://localhost:3001/vote/2023-04-28/arrived
Authorization: Bearer {{jwt}}