# swagger: "2.0"
# info:
#   description: "Study about api"
#   version: "1.0.0"
#   title: "swagger"
# tags:
#   - name: User
#     description: 게시판 API

# paths:
#   /user/active:
#     get:
#       summary: "get active user list"
#       tags: [user]
#       responses:
#         200:
#           description: 조회 결과
#           content:
#             application/json: "content/type"

openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: About api
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: user
    description: Everything about users
paths:
  /user/active:
    put:
      tags:
        - user
      summary: Get active users list
      description: Get active users list
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
      security:
        - petstore_auth:
            - write:pets
            - read:pets
components:
  schemas:
    Notice:
      type: object
      properties:
        from:
          type: string
          example: "231432512"
          description: uid
        to:
          type: string
          example: "231432513"
          description: uid
        type:
          type: string
          enum:
            - like
            - friend
            - alphabet
          example: like
        message:
          type: string
          example: 홍길동님으로부터 좋아요를 받았어요!
        sub:
          type: string
          example: 0/U
        status:
          type: string
          enum:
            - pending
            - refusal
            - approval
            - response
          example: pending
      xml:
        name: order
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pet"
        application/xml:
          schema:
            $ref: "#/components/schemas/Pet"
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/User"
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
