name: day-shcedule
run-name: ${{github.actor}} run schedule
on:
  schedule:
    - cron: "1 0 1 * *"
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: http-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://about-backend.herokuapp.com/admin/manage/monthCalc"
          method: "PATCH"
          bearerToken: ${{secrets.INF_TOKEN}}
          customHeaders: '{"Content-Type": "application/json"}'
          data: "{}"
