name: day-shcedule
run-name: ${{github.actor}} run schedule
on:
  schedule:
    - cron: "50 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: http-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: "http://localhost:3000/admin/manage/daycalc"
          method: "PATCH"
          bearerToken: ${{secrets.GITHUB_TOKEN}}
          customHeaders: '{"Content-Type": "application/json"}'
